$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: train_model
version: 1
type: command

inputs:
  processed_data:
    type: uri_folder

outputs:
  model_output:
    type: uri_folder
  parent_run_id:
    type: uri_file

code: ../../src

environment: azureml:bank-churn-env:1

command: >-
  python train.py
  --data ${{inputs.processed_data}}
  --model-artifact-dir ${{outputs.model_output}}
  --parent-run-id-output ${{outputs.parent_run_id}}
